package com.entities;
// default package
// Generated 3/Mai/2014 21:44:14 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Real generated by hbm2java
 */
@Entity
@Table(name = "real", catalog = "camcof")
public class Real implements java.io.Serializable {

	private Integer idReal;
	private DataContext dataContext;
	private String description;
	private String timeCreation;

	public Real() {
	}

	public Real(DataContext dataContext) {
		this.dataContext = dataContext;
	}

	public Real(DataContext dataContext, String description, String timeCreation) {
		this.dataContext = dataContext;
		this.description = description;
		this.timeCreation = timeCreation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idReal", unique = true, nullable = false)
	public Integer getIdReal() {
		return this.idReal;
	}

	public void setIdReal(Integer idReal) {
		this.idReal = idReal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Data_context_idData_context", nullable = false)
	public DataContext getDataContext() {
		return this.dataContext;
	}

	public void setDataContext(DataContext dataContext) {
		this.dataContext = dataContext;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "timeCreation", length = 45)
	public String getTimeCreation() {
		return this.timeCreation;
	}

	public void setTimeCreation(String timeCreation) {
		this.timeCreation = timeCreation;
	}

}
