package com.entities;
// default package
// Generated 3/Mai/2014 21:44:14 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "user_profile", catalog = "camcof")
public class UserProfile implements java.io.Serializable {

	private Integer idUserProfile;
	private Set<SensingData> sensingDatas = new HashSet<SensingData>(0);

	public UserProfile() {
	}

	public UserProfile(Set<SensingData> sensingDatas) {
		this.sensingDatas = sensingDatas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUser_profile", unique = true, nullable = false)
	public Integer getIdUserProfile() {
		return this.idUserProfile;
	}

	public void setIdUserProfile(Integer idUserProfile) {
		this.idUserProfile = idUserProfile;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfile")
	public Set<SensingData> getSensingDatas() {
		return this.sensingDatas;
	}

	public void setSensingDatas(Set<SensingData> sensingDatas) {
		this.sensingDatas = sensingDatas;
	}

}
